-- Enable FORCE ROW LEVEL SECURITY on all tenant-scoped tables
-- This prevents superusers or certain roles from bypassing RLS policies
-- Required for multi-tenant SaaS data isolation

ALTER TABLE "Tenant" FORCE ROW LEVEL SECURITY;
ALTER TABLE "User" FORCE ROW LEVEL SECURITY;
ALTER TABLE "RefreshToken" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Event" FORCE ROW LEVEL SECURITY;
ALTER TABLE "UsageLine" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Meter" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Invoice" FORCE ROW LEVEL SECURITY;
ALTER TABLE "InvoiceLineItem" FORCE ROW LEVEL SECURITY;
ALTER TABLE "MetricRollup" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ExportAudit" FORCE ROW LEVEL SECURITY;
